name: Deploy App in Develop

on:
  push:
    branches:
      - develop
      - homolog
      - main

jobs:
  deploy:
    runs-on: self-hosted

    strategy:
      matrix:
        environment:
          - develop
          - homolog
          - main

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.10.0'

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Install dependencies
        run: npm install

      - name: Build project for ${{ matrix.environment }}
        run: |
          if [ "${{ matrix.environment }}" == "homolog" ]; then
            npm run build:homolog
          elif [ "${{ matrix.environment }}" == "main" ]; then
            npm run build:prod
          else
            npm run build:dev
          fi

      - name: Determine Deploy Path
        id: set_deploy_path
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=path::/home/bilgiadmin/applications/producao/app"
          elif [ "${{ github.ref }}" == "refs/heads/homolog" ]; then
            echo "::set-output name=path::/home/bilgiadmin/applications/homologacao/app"
          else
            echo "::set-output name=path::/home/bilgiadmin/applications/desenvolvimento/app"
          fi

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
          DEPLOY_PATH: ${{ steps.set_deploy_path.outputs.path }}
        run: |
          sshpass -p "$SERVER_PASSWORD" rsync -avz --delete dist/* $SERVER_USER@$SERVER_IP:$DEPLOY_PATH
